# name: sample-flask
# services:
# - name: web
#   github:
#     repo: digitalocean/sample-flask
#     branch: main

name: bia-sales-analysis
services:
- name: web
  git:
    repo_clone_url: https://github.com/Nyeinchanaung/BIA-Sales-Analysis.git
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm --workers 2 app.app:app
  http_port: 8080
  environment_slug: python
  python_version: "3.12.2"
  apt_packages:
    - python3-dev
    - g++
    - libatlas-base-dev
  health_check:
    http_path: /
    port: 8080
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3